version: "3.9"

services:
  db:
    image: mariadb:11.0.3
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - "3306:3306"
    expose:
      - "3306"

  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:/code
    expose:
      - "8000"
    environment:
      - DEBUG=True
      - MYSQL_HOST=db
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    depends_on:
      - db
